# プロジェクト全体の Gradle 設定。
# IDE（Android Studio など）で行った Gradle の設定は、このファイルの設定より *優先される*。
# ビルド環境の設定について詳しくは次を参照:
# http://www.gradle.org/docs/current/userguide/build_environment.html
# デーモンプロセスの JVM 引数。主にメモリ設定の調整に使う。
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# 有効にすると、Gradle が試験的な並列モードで動く。
# 疎結合なプロジェクトでのみ使うこと。詳しくは次を参照:
# https://developer.android.com/r/tools/gradle-multi-project-decoupled-projects
# org.gradle.parallel=true
# AndroidX のパッケージ構成を使い、Android OS に含まれるパッケージと
# アプリの APK に含まれるパッケージを区別しやすくする
# https://developer.android.com/topic/libraries/support-library/androidx-rn
android.useAndroidX=true
# このプロジェクトの Kotlin コードスタイル（"official" または "obsolete"）
kotlin.code.style=official
# ライブラリごとの R クラスに名前空間を付け、そのライブラリ自身が宣言したリソースだけを含める。
# 依存ライブラリのリソースを含めないため、R クラスが小さくなる
android.nonTransitiveRClass=true