config:
  validation: true
  warningsAsErrors: true

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable', 'Test']
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'

complexity:
  LongParameterList:
    ignoreDefaultParameters: true
  LongMethod:
    ignoreAnnotated: ['Composable']
  TooManyFunctions:
    ignoreAnnotatedFunctions: ['Preview', 'Test']

style:
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreAnnotated: ['Composable', 'Test']
  UnusedPrivateFunction:
    ignoreAnnotated: ['Preview']
